// <auto-generated>
//     Hand-written to match the ResXFileCodeGenerator shape; the CLI build does
//     not run the generator, so this file is committed. One property per resource
//     in Strings.resx.
// </auto-generated>
#nullable enable

using System.Resources;

namespace Timetracker.Plugins.Contracts.Localization;

/// <summary>The user-visible strings of this project.</summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>Returns the cached ResourceManager used by this class.</summary>
    private static ResourceManager ResourceManager => _resourceManager ??= new ResourceManager(
        "Timetracker.Plugins.Contracts.Localization.Strings", typeof(Strings).Assembly);


    /// <summary>Delete {0}?  This removes the sessions from the JSON file and cannot b</summary>
    public static string Confirm_Delete => ResourceManager.GetString(nameof(Confirm_Delete))!;

    /// <summary>Yes</summary>
    public static string Confirm_Yes => ResourceManager.GetString(nameof(Confirm_Yes))!;

    /// <summary>No</summary>
    public static string Confirm_No => ResourceManager.GetString(nameof(Confirm_No))!;

    /// <summary>Cancel</summary>
    public static string Confirm_Cancel => ResourceManager.GetString(nameof(Confirm_Cancel))!;

    /// <summary>Timetracker</summary>
    public static string Confirm_Title => ResourceManager.GetString(nameof(Confirm_Title))!;

    /// <summary>Apply</summary>
    public static string Confirm_Apply => ResourceManager.GetString(nameof(Confirm_Apply))!;

    /// <summary>The sessions are rewritten in the JSON file.</summary>
    public static string Confirm_Rewritten => ResourceManager.GetString(nameof(Confirm_Rewritten))!;
}
