// <auto-generated>
//     Hand-written to match the ResXFileCodeGenerator shape; the CLI build does
//     not run the generator, so this file is committed. One property per resource
//     in Strings.resx.
// </auto-generated>
#nullable enable

using System.Resources;

namespace Timetracker.Plugins.WeekView.Localization;

/// <summary>The user-visible strings of this project.</summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>Returns the cached ResourceManager used by this class.</summary>
    private static ResourceManager ResourceManager => _resourceManager ??= new ResourceManager(
        "Timetracker.Plugins.WeekView.Localization.Strings", typeof(Strings).Assembly);


    /// <summary>Week view</summary>
    public static string Tab_WeekView => ResourceManager.GetString(nameof(Tab_WeekView))!;

    /// <summary>◀ Previous week</summary>
    public static string Week_PreviousWeek => ResourceManager.GetString(nameof(Week_PreviousWeek))!;

    /// <summary>Next week ▶</summary>
    public static string Week_NextWeek => ResourceManager.GetString(nameof(Week_NextWeek))!;

    /// <summary>● Current week</summary>
    public static string Week_CurrentWeek => ResourceManager.GetString(nameof(Week_CurrentWeek))!;

    /// <summary>Book…</summary>
    public static string Week_Book => ResourceManager.GetString(nameof(Week_Book))!;

    /// <summary>Book this untracked time as a session</summary>
    public static string Week_BookToolTip => ResourceManager.GetString(nameof(Week_BookToolTip))!;

    /// <summary>Round ½h</summary>
    public static string Week_Round => ResourceManager.GetString(nameof(Week_Round))!;

    /// <summary>Round the tasks of {0} to half hours?</summary>
    public static string Week_RoundConfirm => ResourceManager.GetString(nameof(Week_RoundConfirm))!;

    /// <summary>Distribute</summary>
    public static string Week_Distribute => ResourceManager.GetString(nameof(Week_Distribute))!;

    /// <summary>Distribute untracked time</summary>
    public static string Week_DistributeTitle => ResourceManager.GetString(nameof(Week_DistributeTitle))!;

    /// <summary>Round each task's time on this day to the nearest half hour</summary>
    public static string Week_RoundingHintIdle => ResourceManager.GetString(nameof(Week_RoundingHintIdle))!;

    /// <summary>Every task on this day is already on a half hour</summary>
    public static string Week_RoundingHintAlready => ResourceManager.GetString(nameof(Week_RoundingHintAlready))!;

    /// <summary>Distribute the day's untracked time over its tasks</summary>
    public static string Week_DistributionHint => ResourceManager.GetString(nameof(Week_DistributionHint))!;

    /// <summary>Nothing to distribute: the day has no untracked time, or no task can a</summary>
    public static string Week_DistributionHintNone => ResourceManager.GetString(nameof(Week_DistributionHintNone))!;

    /// <summary>Copy this element's tasks</summary>
    public static string Week_CopyElementTasks => ResourceManager.GetString(nameof(Week_CopyElementTasks))!;

    /// <summary>Copy this task</summary>
    public static string Week_CopyTask => ResourceManager.GetString(nameof(Week_CopyTask))!;

    /// <summary>Could not access the clipboard.</summary>
    public static string Week_ClipboardError => ResourceManager.GetString(nameof(Week_ClipboardError))!;

    /// <summary>Copied the tracked tasks.</summary>
    public static string Week_Copied => ResourceManager.GetString(nameof(Week_Copied))!;

    /// <summary>Could not copy: {0}</summary>
    public static string Week_CopyFailed => ResourceManager.GetString(nameof(Week_CopyFailed))!;

    /// <summary>Skipped: </summary>
    public static string Week_Skipped => ResourceManager.GetString(nameof(Week_Skipped))!;

    /// <summary>Nothing could be distributed.</summary>
    public static string Week_NothingToDistribute => ResourceManager.GetString(nameof(Week_NothingToDistribute))!;

    /// <summary>Nothing could be rounded. </summary>
    public static string Week_NothingToRound => ResourceManager.GetString(nameof(Week_NothingToRound))!;

    /// <summary>✓ Distributed {0} over {1} task(s) on {2}.</summary>
    public static string Week_Distributed => ResourceManager.GetString(nameof(Week_Distributed))!;

    /// <summary>✓ Rounded {0} task(s) on {1} to half hours.{2}</summary>
    public static string Week_Rounded => ResourceManager.GetString(nameof(Week_Rounded))!;

    /// <summary>Σ {0}</summary>
    public static string Week_TotalText => ResourceManager.GetString(nameof(Week_TotalText))!;

    /// <summary>Week {0} · {1}</summary>
    public static string Week_HeaderTitle => ResourceManager.GetString(nameof(Week_HeaderTitle))!;

    /// <summary>PC active time that no tracked session covers</summary>
    public static string Week_UntrackedToolTip => ResourceManager.GetString(nameof(Week_UntrackedToolTip))!;

    /// <summary>Distribute</summary>
    public static string DistributeDay_Apply => ResourceManager.GetString(nameof(DistributeDay_Apply))!;

    /// <summary>Cancel</summary>
    public static string DistributeDay_Cancel => ResourceManager.GetString(nameof(DistributeDay_Cancel))!;

    /// <summary>Task</summary>
    public static string DistributeDay_TaskHeader => ResourceManager.GetString(nameof(DistributeDay_TaskHeader))!;

    /// <summary>Now</summary>
    public static string DistributeDay_NowHeader => ResourceManager.GetString(nameof(DistributeDay_NowHeader))!;

    /// <summary>The task's total once its assigned share is applied</summary>
    public static string DistributeDay_TotalFallback => ResourceManager.GetString(nameof(DistributeDay_TotalFallback))!;

    /// <summary>Take 15 minutes back</summary>
    public static string DistributeDay_MinusToolTip => ResourceManager.GetString(nameof(DistributeDay_MinusToolTip))!;

    /// <summary>Add 15 minutes to this task</summary>
    public static string DistributeDay_PlusToolTip => ResourceManager.GetString(nameof(DistributeDay_PlusToolTip))!;

    /// <summary>{0} removed</summary>
    public static string Week_ChangeRemovedFormat => ResourceManager.GetString(nameof(Week_ChangeRemovedFormat))!;

    /// <summary>&lt;None></summary>
    public static string Week_NoBookingElement => ResourceManager.GetString(nameof(Week_NoBookingElement))!;

    /// <summary>⚠ {0} untracked ({1})</summary>
    public static string Week_GapWarning => ResourceManager.GetString(nameof(Week_GapWarning))!;

    /// <summary>no free time next to its last session</summary>
    public static string Week_DistributeBlocked => ResourceManager.GetString(nameof(Week_DistributeBlocked))!;

    /// <summary>{0} untracked</summary>
    public static string Week_DistributeUntracked => ResourceManager.GetString(nameof(Week_DistributeUntracked))!;

    /// <summary>left {0}</summary>
    public static string Week_DistributeLeft => ResourceManager.GetString(nameof(Week_DistributeLeft))!;

    /// <summary>Book untracked time</summary>
    public static string BookGap_Title => ResourceManager.GetString(nameof(BookGap_Title))!;

    /// <summary>The PC was active here without a tracked session. Adjust the times if </summary>
    public static string BookGap_Hint => ResourceManager.GetString(nameof(BookGap_Hint))!;

    /// <summary>Start</summary>
    public static string BookGap_Start => ResourceManager.GetString(nameof(BookGap_Start))!;

    /// <summary>End</summary>
    public static string BookGap_End => ResourceManager.GetString(nameof(BookGap_End))!;

    /// <summary>Duration</summary>
    public static string BookGap_Duration => ResourceManager.GetString(nameof(BookGap_Duration))!;

    /// <summary>Task</summary>
    public static string BookGap_Task => ResourceManager.GetString(nameof(BookGap_Task))!;

    /// <summary>Booking element</summary>
    public static string BookGap_BookingElement => ResourceManager.GetString(nameof(BookGap_BookingElement))!;

    /// <summary>Book</summary>
    public static string BookGap_Book => ResourceManager.GetString(nameof(BookGap_Book))!;

    /// <summary>Cancel</summary>
    public static string BookGap_Cancel => ResourceManager.GetString(nameof(BookGap_Cancel))!;

    /// <summary>{0} ({1})</summary>
    public static string Week_NodeCaption => ResourceManager.GetString(nameof(Week_NodeCaption))!;
}
