// <auto-generated>
//     Hand-written to match the ResXFileCodeGenerator shape; the CLI build does
//     not run the generator, so this file is committed. One property per resource
//     in Strings.resx.
// </auto-generated>
#nullable enable

using System.Resources;

namespace Timetracker.App.Localization;

/// <summary>The user-visible strings of this project.</summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>Returns the cached ResourceManager used by this class.</summary>
    private static ResourceManager ResourceManager => _resourceManager ??= new ResourceManager(
        "Timetracker.App.Localization.Strings", typeof(Strings).Assembly);


    /// <summary>▶ Start</summary>
    public static string Tracker_Start => ResourceManager.GetString(nameof(Tracker_Start))!;

    /// <summary>■ Stop</summary>
    public static string Tracker_Stop => ResourceManager.GetString(nameof(Tracker_Stop))!;

    /// <summary>◀ Previous</summary>
    public static string Tracker_Previous => ResourceManager.GetString(nameof(Tracker_Previous))!;

    /// <summary>Next ▶</summary>
    public static string Tracker_Next => ResourceManager.GetString(nameof(Tracker_Next))!;

    /// <summary>Please enter a task name first.</summary>
    public static string Tracker_EmptyTask => ResourceManager.GetString(nameof(Tracker_EmptyTask))!;

    /// <summary>Timetracker</summary>
    public static string Tracker_InvalidTaskTitle => ResourceManager.GetString(nameof(Tracker_InvalidTaskTitle))!;

    /// <summary>OK</summary>
    public static string Tracker_InvalidTaskOk => ResourceManager.GetString(nameof(Tracker_InvalidTaskOk))!;

    /// <summary>00:00:00</summary>
    public static string Tracker_TimerZero => ResourceManager.GetString(nameof(Tracker_TimerZero))!;

    /// <summary>Timetracker</summary>
    public static string App_Title => ResourceManager.GetString(nameof(App_Title))!;

    /// <summary>Tracker</summary>
    public static string App_TabTracker => ResourceManager.GetString(nameof(App_TabTracker))!;

    /// <summary>Options</summary>
    public static string App_TabOptions => ResourceManager.GetString(nameof(App_TabOptions))!;

    /// <summary>Edit entries – {0}</summary>
    public static string EditEntries_Title => ResourceManager.GetString(nameof(EditEntries_Title))!;

    /// <summary>Adjust the start and end times; the duration is recalculated. Use ✕ to</summary>
    public static string EditEntries_Hint => ResourceManager.GetString(nameof(EditEntries_Hint))!;

    /// <summary>The end time must not be before the start time.</summary>
    public static string EditEntries_EndBeforeStart => ResourceManager.GetString(nameof(EditEntries_EndBeforeStart))!;

    /// <summary>Save</summary>
    public static string EditEntries_Save => ResourceManager.GetString(nameof(EditEntries_Save))!;

    /// <summary>Cancel</summary>
    public static string EditEntries_Cancel => ResourceManager.GetString(nameof(EditEntries_Cancel))!;

    /// <summary>Delete</summary>
    public static string EditEntries_Delete => ResourceManager.GetString(nameof(EditEntries_Delete))!;

    /// <summary>Delete the session {0} – {1} ({2})?</summary>
    public static string EditEntries_DeleteConfirm => ResourceManager.GetString(nameof(EditEntries_DeleteConfirm))!;

    /// <summary>Delete this session</summary>
    public static string EditEntries_DeletionToolTip => ResourceManager.GetString(nameof(EditEntries_DeletionToolTip))!;

    /// <summary>Task</summary>
    public static string EditEntries_TaskHeader => ResourceManager.GetString(nameof(EditEntries_TaskHeader))!;

    /// <summary>Start</summary>
    public static string EditEntries_StartHeader => ResourceManager.GetString(nameof(EditEntries_StartHeader))!;

    /// <summary>End</summary>
    public static string EditEntries_EndHeader => ResourceManager.GetString(nameof(EditEntries_EndHeader))!;

    /// <summary>Duration</summary>
    public static string EditEntries_DurationHeader => ResourceManager.GetString(nameof(EditEntries_DurationHeader))!;

    /// <summary>Task</summary>
    public static string Grid_CaptionTask => ResourceManager.GetString(nameof(Grid_CaptionTask))!;

    /// <summary>Booking element</summary>
    public static string Grid_CaptionBookingElement => ResourceManager.GetString(nameof(Grid_CaptionBookingElement))!;

    /// <summary>Started</summary>
    public static string Grid_CaptionStarted => ResourceManager.GetString(nameof(Grid_CaptionStarted))!;

    /// <summary>Ended</summary>
    public static string Grid_CaptionEnded => ResourceManager.GetString(nameof(Grid_CaptionEnded))!;

    /// <summary>Duration</summary>
    public static string Grid_CaptionDuration => ResourceManager.GetString(nameof(Grid_CaptionDuration))!;

    /// <summary>Edit this item's entries</summary>
    public static string Grid_EditToolTip => ResourceManager.GetString(nameof(Grid_EditToolTip))!;

    /// <summary>Start timing this task</summary>
    public static string Grid_StartToolTip => ResourceManager.GetString(nameof(Grid_StartToolTip))!;

    /// <summary>Filter by {0}</summary>
    public static string Grid_FilterBy => ResourceManager.GetString(nameof(Grid_FilterBy))!;

    /// <summary>Task name</summary>
    public static string TaskInput_Placeholder => ResourceManager.GetString(nameof(TaskInput_Placeholder))!;

    /// <summary>Save</summary>
    public static string Options_Save => ResourceManager.GetString(nameof(Options_Save))!;

    /// <summary>Show in explorer</summary>
    public static string Options_ExplorerToolTip => ResourceManager.GetString(nameof(Options_ExplorerToolTip))!;

    /// <summary>Hint for {0}</summary>
    public static string Options_HintAutomationName => ResourceManager.GetString(nameof(Options_HintAutomationName))!;

    /// <summary>Timetracker</summary>
    public static string SingleInstance_Title => ResourceManager.GetString(nameof(SingleInstance_Title))!;

    /// <summary>Timetracker is already running.</summary>
    public static string SingleInstance_Message => ResourceManager.GetString(nameof(SingleInstance_Message))!;

    /// <summary>Entries are appended to {0}</summary>
    public static string Tracker_EntriesAppended => ResourceManager.GetString(nameof(Tracker_EntriesAppended))!;

    /// <summary>✓ Deleted {0}</summary>
    public static string Tracker_Deleted => ResourceManager.GetString(nameof(Tracker_Deleted))!;

    /// <summary>✗ Delete failed: {0}</summary>
    public static string Tracker_DeleteFailed => ResourceManager.GetString(nameof(Tracker_DeleteFailed))!;

    /// <summary>✓ Updated "{0}"</summary>
    public static string Tracker_Updated => ResourceManager.GetString(nameof(Tracker_Updated))!;

    /// <summary>✗ Update failed: {0}</summary>
    public static string Tracker_UpdateFailed => ResourceManager.GetString(nameof(Tracker_UpdateFailed))!;

    /// <summary>Could not delete the entry: {0}</summary>
    public static string Tracker_ErrorDeleteEntry => ResourceManager.GetString(nameof(Tracker_ErrorDeleteEntry))!;

    /// <summary>Could not save the changes: {0}</summary>
    public static string Tracker_ErrorSaveChanges => ResourceManager.GetString(nameof(Tracker_ErrorSaveChanges))!;

    /// <summary>Could not save the change: {0}</summary>
    public static string Tracker_ErrorSaveChange => ResourceManager.GetString(nameof(Tracker_ErrorSaveChange))!;

    /// <summary>Could not save the entry: {0}</summary>
    public static string Tracker_ErrorSaveEntry => ResourceManager.GetString(nameof(Tracker_ErrorSaveEntry))!;

    /// <summary>✓ Saved {0} to {1}</summary>
    public static string Tracker_Saved => ResourceManager.GetString(nameof(Tracker_Saved))!;

    /// <summary>✗ Save failed: {0}</summary>
    public static string Tracker_SaveFailed => ResourceManager.GetString(nameof(Tracker_SaveFailed))!;

    /// <summary>Tracking "{0}" since {1:HH:mm:ss} …</summary>
    public static string Tracker_TrackingSince => ResourceManager.GetString(nameof(Tracker_TrackingSince))!;

    /// <summary>Timetracker – {0}</summary>
    public static string Tracker_WindowTitleRunning => ResourceManager.GetString(nameof(Tracker_WindowTitleRunning))!;

    /// <summary>"{0}" (all {1} sessions)</summary>
    public static string Tracker_DeleteSummarySingle => ResourceManager.GetString(nameof(Tracker_DeleteSummarySingle))!;

    /// <summary>{0} tasks ({1} sessions)</summary>
    public static string Tracker_DeleteSummaryMulti => ResourceManager.GetString(nameof(Tracker_DeleteSummaryMulti))!;

    /// <summary>(without task)</summary>
    public static string EditEntries_WithoutTask => ResourceManager.GetString(nameof(EditEntries_WithoutTask))!;

    /// <summary>session</summary>
    public static string EditEntries_SessionSingle => ResourceManager.GetString(nameof(EditEntries_SessionSingle))!;

    /// <summary>sessions</summary>
    public static string EditEntries_SessionPlural => ResourceManager.GetString(nameof(EditEntries_SessionPlural))!;

    /// <summary>Page {0} of {1}</summary>
    public static string Status_Paging => ResourceManager.GetString(nameof(Status_Paging))!;

    /// <summary>Options saved.</summary>
    public static string Options_Saved => ResourceManager.GetString(nameof(Options_Saved))!;

    /// <summary>Could not save the options: {0}</summary>
    public static string Options_SaveFailed => ResourceManager.GetString(nameof(Options_SaveFailed))!;

    /// <summary>General</summary>
    public static string Options_SectionGeneral => ResourceManager.GetString(nameof(Options_SectionGeneral))!;

    /// <summary>Tracking file</summary>
    public static string Options_TrackingFile => ResourceManager.GetString(nameof(Options_TrackingFile))!;

    /// <summary>Options file</summary>
    public static string Options_OptionsFile => ResourceManager.GetString(nameof(Options_OptionsFile))!;

    /// <summary>Log folder</summary>
    public static string Options_LogFolder => ResourceManager.GetString(nameof(Options_LogFolder))!;

    /// <summary>The tracked sessions are stored in this JSON file.</summary>
    public static string Options_TrackingFileHint => ResourceManager.GetString(nameof(Options_TrackingFileHint))!;

    /// <summary>The options are stored in this JSON file.</summary>
    public static string Options_OptionsFileHint => ResourceManager.GetString(nameof(Options_OptionsFileHint))!;

    /// <summary>Diagnostic log files are written to this folder.</summary>
    public static string Options_LogFolderHint => ResourceManager.GetString(nameof(Options_LogFolderHint))!;
}
