// <auto-generated>
//     Hand-written to match the ResXFileCodeGenerator shape; the CLI build does
//     not run the generator, so this file is committed. One property per resource
//     in Strings.resx.
// </auto-generated>
#nullable enable

using System.Resources;

namespace Timetracker.Plugins.AzureDevOps.Localization;

/// <summary>The user-visible strings of this project.</summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>Returns the cached ResourceManager used by this class.</summary>
    private static ResourceManager ResourceManager => _resourceManager ??= new ResourceManager(
        "Timetracker.Plugins.AzureDevOps.Localization.Strings", typeof(Strings).Assembly);


    /// <summary>Azure DevOps import</summary>
    public static string AzureDevOps_PanelTitle => ResourceManager.GetString(nameof(AzureDevOps_PanelTitle))!;

    /// <summary>Fetches issue number, title and AZE-Element into the fields. The conne</summary>
    public static string AzureDevOps_ImportToolTip => ResourceManager.GetString(nameof(AzureDevOps_ImportToolTip))!;

    /// <summary>Azure DevOps import</summary>
    public static string AzureDevOps_WindowTitle => ResourceManager.GetString(nameof(AzureDevOps_WindowTitle))!;

    /// <summary>Issue number</summary>
    public static string AzureDevOps_Watermark => ResourceManager.GetString(nameof(AzureDevOps_Watermark))!;

    /// <summary>Import</summary>
    public static string AzureDevOps_Import => ResourceManager.GetString(nameof(AzureDevOps_Import))!;

    /// <summary>Cancel</summary>
    public static string AzureDevOps_Cancel => ResourceManager.GetString(nameof(AzureDevOps_Cancel))!;

    /// <summary>Issue number:</summary>
    public static string AzureDevOps_IssueLabel => ResourceManager.GetString(nameof(AzureDevOps_IssueLabel))!;

    /// <summary>Please enter a numeric issue number.</summary>
    public static string AzureDevOps_NumericRequired => ResourceManager.GetString(nameof(AzureDevOps_NumericRequired))!;

    /// <summary>✗ {0}</summary>
    public static string AzureDevOps_StatusErrorPrefix => ResourceManager.GetString(nameof(AzureDevOps_StatusErrorPrefix))!;

    /// <summary>Azure DevOps is not configured. Enter the organization URL, project an</summary>
    public static string AzureDevOps_NotConfigured => ResourceManager.GetString(nameof(AzureDevOps_NotConfigured))!;

    /// <summary>Please enter a numeric issue number first.</summary>
    public static string AzureDevOps_NumericFirst => ResourceManager.GetString(nameof(AzureDevOps_NumericFirst))!;

    /// <summary>Azure DevOps request failed: {0}</summary>
    public static string AzureDevOps_RequestFailed => ResourceManager.GetString(nameof(AzureDevOps_RequestFailed))!;

    /// <summary>Work item {0} was not found.</summary>
    public static string AzureDevOps_WorkItemNotFound => ResourceManager.GetString(nameof(AzureDevOps_WorkItemNotFound))!;

    /// <summary>✓ Applied "{0}"{1}</summary>
    public static string AzureDevOps_Applied => ResourceManager.GetString(nameof(AzureDevOps_Applied))!;

    /// <summary>Azure DevOps</summary>
    public static string AzureDevOps_Section => ResourceManager.GetString(nameof(AzureDevOps_Section))!;

    /// <summary>Organization URL</summary>
    public static string AzureDevOps_UrlLabel => ResourceManager.GetString(nameof(AzureDevOps_UrlLabel))!;

    /// <summary>Project</summary>
    public static string AzureDevOps_ProjectLabel => ResourceManager.GetString(nameof(AzureDevOps_ProjectLabel))!;

    /// <summary>Personal access token</summary>
    public static string AzureDevOps_PatLabel => ResourceManager.GetString(nameof(AzureDevOps_PatLabel))!;

    /// <summary>Booking element field</summary>
    public static string AzureDevOps_BookingElementFieldLabel => ResourceManager.GetString(nameof(AzureDevOps_BookingElementFieldLabel))!;

    /// <summary>e.g. https://dev.azure.com/your-org</summary>
    public static string AzureDevOps_UrlHint => ResourceManager.GetString(nameof(AzureDevOps_UrlHint))!;

    /// <summary>Azure DevOps personal access token; used as Basic password, user name </summary>
    public static string AzureDevOps_PatHint => ResourceManager.GetString(nameof(AzureDevOps_PatHint))!;

    /// <summary>Reference name of the custom field holding the booking element</summary>
    public static string AzureDevOps_BookingElementFieldHint => ResourceManager.GetString(nameof(AzureDevOps_BookingElementFieldHint))!;
}
