<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Timetracker.AzureDevOps</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="azure-favicon.ico" />
  </ItemGroup>

</Project>