// <auto-generated>
//     Hand-written to match the ResXFileCodeGenerator shape; the CLI build does
//     not run the generator, so this file is committed. One property per resource
//     in Strings.resx.
// </auto-generated>
#nullable enable

using System.Resources;

namespace Timetracker.Plugins.ActivityMonitor.Localization;

/// <summary>The user-visible strings of this project.</summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>Returns the cached ResourceManager used by this class.</summary>
    private static ResourceManager ResourceManager => _resourceManager ??= new ResourceManager(
        "Timetracker.Plugins.ActivityMonitor.Localization.Strings", typeof(Strings).Assembly);


    /// <summary>⏻ Install PC activity monitor</summary>
    public static string ActivityMon_Install => ResourceManager.GetString(nameof(ActivityMon_Install))!;

    /// <summary>⏻ Remove PC activity monitor</summary>
    public static string ActivityMon_Remove => ResourceManager.GetString(nameof(ActivityMon_Remove))!;

    /// <summary>✓ The PC activity monitor will start automatically.</summary>
    public static string ActivityMon_InstallOk => ResourceManager.GetString(nameof(ActivityMon_InstallOk))!;

    /// <summary>✗ Installation failed. Make sure "{0}" exists next to the app.</summary>
    public static string ActivityMon_InstallFailed => ResourceManager.GetString(nameof(ActivityMon_InstallFailed))!;

    /// <summary>✓ The PC activity monitor autostart was removed.</summary>
    public static string ActivityMon_UninstallOk => ResourceManager.GetString(nameof(ActivityMon_UninstallOk))!;

    /// <summary>✗ Removing the autostart entry failed.</summary>
    public static string ActivityMon_UninstallFailed => ResourceManager.GetString(nameof(ActivityMon_UninstallFailed))!;

    /// <summary>Monitoring is installed (starts automatically at logon).</summary>
    public static string ActivityMon_Installed => ResourceManager.GetString(nameof(ActivityMon_Installed))!;

    /// <summary>The monitor is not installed; PC activity is only recorded while it ru</summary>
    public static string ActivityMon_NotInstalled => ResourceManager.GetString(nameof(ActivityMon_NotInstalled))!;

    /// <summary>Activity monitor</summary>
    public static string ActivityMon_Section => ResourceManager.GetString(nameof(ActivityMon_Section))!;

    /// <summary>Uninstalled</summary>
    public static string ActivityMon_StatusUninstalled => ResourceManager.GetString(nameof(ActivityMon_StatusUninstalled))!;

    /// <summary>Stopped</summary>
    public static string ActivityMon_StatusStopped => ResourceManager.GetString(nameof(ActivityMon_StatusStopped))!;

    /// <summary>Running</summary>
    public static string ActivityMon_StatusRunning => ResourceManager.GetString(nameof(ActivityMon_StatusRunning))!;

    /// <summary>Unknown</summary>
    public static string ActivityMon_StatusUnknown => ResourceManager.GetString(nameof(ActivityMon_StatusUnknown))!;

    /// <summary>Idle span threshold (minutes)</summary>
    public static string ActivityMon_IdleSpanLabel => ResourceManager.GetString(nameof(ActivityMon_IdleSpanLabel))!;

    /// <summary>Idle stop threshold (minutes)</summary>
    public static string ActivityMon_IdleStopLabel => ResourceManager.GetString(nameof(ActivityMon_IdleStopLabel))!;

    /// <summary>Activity file</summary>
    public static string ActivityMon_ActivityFileLabel => ResourceManager.GetString(nameof(ActivityMon_ActivityFileLabel))!;

    /// <summary>State file</summary>
    public static string ActivityMon_StateFileLabel => ResourceManager.GetString(nameof(ActivityMon_StateFileLabel))!;

    /// <summary>Idle stretches shorter than this are not written to the activity log; </summary>
    public static string ActivityMon_IdleSpanHint => ResourceManager.GetString(nameof(ActivityMon_IdleSpanHint))!;

    /// <summary>A running session with no input for this long is stopped and back-date</summary>
    public static string ActivityMon_IdleStopHint => ResourceManager.GetString(nameof(ActivityMon_IdleStopHint))!;

    /// <summary>The recorded active/idle spans are appended to this JSON file.</summary>
    public static string ActivityMon_ActivityFileHint => ResourceManager.GetString(nameof(ActivityMon_ActivityFileHint))!;

    /// <summary>The monitor's last state is kept here so an open span is closed after </summary>
    public static string ActivityMon_StateFileHint => ResourceManager.GetString(nameof(ActivityMon_StateFileHint))!;

    /// <summary>PC {0} active</summary>
    public static string ActivityMon_DaySummaryActive => ResourceManager.GetString(nameof(ActivityMon_DaySummaryActive))!;

    /// <summary>PC {0} active · {1} idle</summary>
    public static string ActivityMon_DaySummaryIdle => ResourceManager.GetString(nameof(ActivityMon_DaySummaryIdle))!;
}
